language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
- pypy3
env:
- DJANGO=">=1.4,<1.5"
- DJANGO=">=1.6,<1.7"
- DJANGO=">=1.7,<1.8"
install:
- pip install gitversion
- pip install "Django${DJANGO}"
- pip install .
- pip install coveralls
script:
- python setup.py test
after_success:
- coveralls
matrix:
  exclude:
  - python: 2.6
    env: DJANGO=">=1.7,<1.8"
  - python: 3.2
    env: DJANGO=">=1.4,<1.5"
  - python: 3.3
    env: DJANGO=">=1.4,<1.5"
  - python: pypy3
    env: DJANGO=">=1.4,<1.5"
deploy:
  provider: pypi
  user: ocadotechnology
  password:
    secure: kdfRG0+3xsH4DSlTtVi8WT8/vhTzlfC58c0gP/MhsrN7k7ffGs6fjxkUoKpIGPZXV+v9kI5elYkFs4wInOrtq5ZgPHKMTpaHxQLrDtCkurYY7mD0e9KP2xVjvPEDQxDrynn1/x75Doi0Oe9StJ5E2odUJ0HcOwqhlKXJuOZa19M=
  distributions: "bdist_wheel sdist"
  on:
    all_branches: true
    repo: ocadotechnology/django-closuretree
    tags: true
    condition: "$DJANGO = '>=1.7,<1.8'"
